### ISSUE TITLE
create new association/table linking ratings to users who inputed the rating, the associated document, and the rating itself (estimated time: 1-2 days)

### ISSUE THREAD

**Issue by YiHanna** [CMU-313/fall22-hw3-team-teedy-us#1]
The acceptance criteria is that a table exists containing a rating, user ID attribute linking the reviewer who inputted the rating, and a document id field linking to the document that is being scored. We will create a test file and try to create rows within the database and see if that is possible.

**Comment by aneshas01** [comment]
Our process is as follows:

1. Set up a form of communication through a text message group chat. All communications about assignments, deadlines, and meeting changes will be done here. 
2. Send out a WhenToMeet to poll each member on their availability throughout the week. The member who sent the WhenToMeet will send a text in the group chat consisting of a date and time for the initial meeting. 
3. Create a Google Doc for brainstorming/planning and share it with team members ahead of the meeting. Make sure that all team members are added on GitHub to the project, and that the repository has been created. 
4. Conduct the initial sprint planning meeting. During this meeting, team members will brainstorm ideas of what features to implement, run Teedy and rank the feasibility of these features, then vote on which feature we should implement. We will sketch out the design of the feature roughly and map out how we want it to look like. A backlog will be constructed during the meeting as a team with times of tasks specified. Roles and responsibilities for the different parts of the project (creating a writing, documenting the process, creating a backlog, and tackling front end, middleware, and backend code, and writing tests) will be delegated to each team member. A WhenToMeet will be sent directly after this meeting, and a due date for select responsibilities will be written in the groupchat. 
5. During the in-between work period before the next meeting, an initial process plan will be created and the code needed for each part of the project will be specified in the shared document. Team members will document their changes by committing their own branch to GitHub with proper descriptions, assigning their changes to the issue, creating pull requests and requesting code reviews. The back-end of the project will be executed first,  then the middleware, and then the front end to make sure that the front end code has a foundation and a connection to the backend. Tests will be created alongside the code being written to make sure that no tests are left out. 
6. Every team member’s changes will be reviewed by the rest of the team members before being pushed to the main branch. The team will regularly coordinate with the TA on Slack and ask any technical questions on Slack to make sure members are on the right track.
7. A minimum of 3 meetings will be held over the course of the project. The second meeting will be a progress check, where team members will explain what they completed and how they did it, and state if they need any help. Meeting minutes will be updated to track any changes in who is assigned to what task, and how much time is left. 
8. Step 5 of making changes, committing, creating pull requests and code reviews will be repeated for other changes. All changes will be done before the third meeting. 
9. The third meeting will consist of team members finalizing all changes. All remaining code reviews and pull requests will be made during the meeting, and a final decision will be made to push the code to the main branch. If the code is not done by the third meeting, team members can decide to hold another meeting in order to finalize the tasks. 
10. The functionality of the project will be thoroughly tested in the last meeting, with all team members making sure that naming conventions and code changes are appropriate and contribute to the project. Requirements of the project will be restated and team members will make sure they have every base covered, and finalize their submission. 
11. At the end of the project, team members will fill out the reflection and remind each other to do so.

**Comment by aneshas01** [comment]
Update and change on 10/4/22: we had an issue with having any reviewers with IDs (unknown beforehand) able to add a score, which made it difficult to distinguish between reviewers and assign them the ability to add scores. The idea to fix this issue is to create 4 admins that are the board of reviewers, and are the only 4 reviewers that have access to all the documents and can add scores. Their ID attribute will be hardcoded in the database so that we are able to focus on the main scope of our issue, which is inputting and displaying the reviewers' scores. We contacted our TA Angela on Slack, and she has approved this change.

**Comment by YiHanna** [comment]
I took 2 days to implement this change on the branch Hanna-database-changes.
